"""
다국어 지원 기능
"""
import streamlit as st
from typing import Dict, Any

# 지원 언어 정의
SUPPORTED_LANGUAGES = {
    "한국어": "ko",
    "English": "en",
    "日本語": "ja",
    "中文": "zh"
}

# 번역 데이터
TRANSLATIONS = {
    "ko": {
        "title": "🔬 HITRAN CRDS Simulator",
        "simulation_settings": "⚙️ 시뮬레이션 설정",
        "spectrometer_type": "분광기 종류",
        "analysis_mode": "📊 분석 모드",
        "temperature": "온도 (K)",
        "wavelength_min": "파장 최소 (nm)",
        "wavelength_max": "파장 최대 (nm)",
        "resolution_settings": "🔬 해상도 설정",
        "resolution_mode": "해상도 모드",
        "matrix_gas_settings": "🌬️ Matrix Gas 설정",
        "matrix_gas_type": "Matrix Gas 종류",
        "total_pressure": "총 압력 (torr)",
        "molecule_selection": "분자 선택",
        "concentration": "농도 (ppb)",
        "run_simulation": "🧮 혼합 스펙트럼 계산",
        "run_analysis": "📈 농도별 분석 실행",
        "calculating": "계산 중...",
        "results": "📊 결과",
        "mixed_spectrum": "🧪 혼합 스펙트럼",
        "concentration_analysis": "📈 농도별 분석",
        "basic_hitran": "🌟 기본 HITRAN",
        "spectrometer": "🔬 분광기",
        "fast": "⚡ 빠른",
        "standard": "🎯 표준",
        "high_resolution": "🔬 고해상도",
        "maximum_resolution": "🚀 최대 해상도",
        "air": "공기 (Air)",
        "cda": "청정건조공기 (Clean Dry Air)",
        "n2": "질소 (N₂)",
        "o2": "산소 (O₂)",
        "he": "헬륨 (He)",
        "h2": "수소 (H₂)",
        "ar": "아르곤 (Ar)",
        "co2": "이산화탄소 (CO₂)",
        "zero_air": "제로에어 (Zero Air)",
        "experimental_data": "📁 실험 데이터",
        "line_analysis": "📋 라인 분석",
        "parameter_sweep": "🌡️ 파라미터 스윕",
        "export": "💾 내보내기",
        "upload_experimental": "실험 데이터 파일 선택 (CSV, TXT)",
        "data_preview": "데이터 미리보기",
        "column_mapping": "데이터 컬럼 매핑",
        "wavelength_column": "파장 컬럼 선택",
        "intensity_column": "흡광도/투과도 컬럼 선택",
        "data_type": "데이터 타입",
        "absorbance": "흡광도 (Absorbance)",
        "transmittance": "투과도 (Transmittance)",
        "transmittance_percent": "투과율 (%)",
        "experiment_vs_simulation": "🔍 실험 vs 시뮬레이션 비교",
        "show_experimental": "실험 데이터 표시",
        "normalize_data": "데이터 정규화",
        "comparison_statistics": "📊 비교 통계",
        "correlation": "상관계수",
        "rms_error": "RMS 오차",
        "mean_absolute_error": "평균 절대 오차",
        "line_details": "📋 라인 상세 정보",
        "line_statistics": "📊 라인 통계",
        "total_lines": "총 라인 수",
        "average_wavelength": "평균 파장",
        "max_absorbance": "최대 흡광도",
        "frequency_range": "주파수 범위",
        "line_distribution": "📈 라인 분포",
        "wavelength_distribution": "파장 분포",
        "frequency_distribution": "주파수 분포",
        "advanced_line_analysis": "🔬 고급 라인 분석",
        "analysis_type": "분석 유형",
        "peak_analysis": "라인 피크 분석",
        "spectrum_fitting": "스펙트럼 피팅",
        "intensity_comparison": "라인 강도 비교",
        "temperature_dependence": "온도 의존성",
        "temperature_sweep": "🌡️ 온도 스윕",
        "pressure_sweep": "🌬️ 압력 스윕",
        "temperature_pressure_sweep": "🌡️🌬️ 온도+압력 스윕",
        "sweep_type": "스윕 타입",
        "min_temperature": "최소 온도 (K)",
        "max_temperature": "최대 온도 (K)",
        "temperature_steps": "온도 단계 수",
        "fixed_pressure": "고정 압력 설정",
        "pressure": "압력 (torr)",
        "min_pressure": "최소 압력 (torr)",
        "max_pressure": "최대 압력 (torr)",
        "pressure_steps": "압력 단계 수",
        "fixed_temperature": "고정 온도 설정",
        "temperature_range": "온도 범위",
        "pressure_range": "압력 범위",
        "run_sweep": "🌡️ 파라미터 스윕 실행",
        "sweep_calculating": "파라미터 스윕 계산 중...",
        "sweep_results": "📊 스윕 분석 결과",
        "temperature_sweep_spectrum": "온도 스윕 스펙트럼",
        "pressure_sweep_spectrum": "압력 스윕 스펙트럼",
        "max_absorbance_vs_temperature": "최대 흡광도 vs 온도",
        "peak_position_vs_temperature": "피크 위치 vs 온도",
        "temperature_dependence_analysis": "📈 온도 의존성 분석",
        "temperature_sensitivity": "온도 민감도",
        "max_absorbance_vs_pressure": "최대 흡광도 vs 압력",
        "peak_position_vs_pressure": "피크 위치 vs 압력",
        "temperature_pressure_dependence": "온도-압력 의존성 히트맵",
        "temperature_pressure_3d": "온도-압력 의존성 3D 서피스",
        "optimal_conditions": "🎯 최적 조건",
        "optimal_temperature": "최적 온도",
        "optimal_pressure": "최적 압력",
        "csv_download": "📊 CSV 데이터 다운로드",
        "png_download": "📈 PNG 그래프 다운로드",
        "pdf_download": "📄 PDF 리포트 다운로드",
        "download_csv": "📥 CSV 파일 다운로드",
        "download_png": "📥 PNG 파일 다운로드",
        "language_selection": "🌐 언어 선택",
        "select_language": "언어를 선택하세요",
        "no_data": "데이터가 없습니다",
        "no_results": "결과가 없습니다",
        "error": "오류",
        "warning": "경고",
        "info": "정보",
        "success": "성공",
        "loading": "로딩 중...",
        "please_wait": "잠시 기다려주세요...",
        "file_upload_error": "파일 업로드 오류",
        "calculation_error": "계산 오류",
        "data_processing_error": "데이터 처리 오류",
        "feature_coming_soon": "이 기능은 향후 업데이트 예정입니다",
        "single_molecule_only": "단일 분자 분석 모드에서만 사용 가능합니다",
        "run_simulation_first": "시뮬레이션을 먼저 실행한 후 사용하세요",
        "no_experimental_data": "선택된 파장 범위에 실험 데이터가 없습니다",
        "no_simulation_results": "비교할 시뮬레이션 결과가 없습니다",
        "statistics_calculation_error": "통계 계산 오류",
        "fitting_error": "피팅 오류"
    },
    "en": {
        "title": "🔬 HITRAN CRDS Simulator",
        "simulation_settings": "⚙️ Simulation Settings",
        "spectrometer_type": "Spectrometer Type",
        "analysis_mode": "📊 Analysis Mode",
        "temperature": "Temperature (K)",
        "wavelength_min": "Wavelength Min (nm)",
        "wavelength_max": "Wavelength Max (nm)",
        "resolution_settings": "🔬 Resolution Settings",
        "resolution_mode": "Resolution Mode",
        "matrix_gas_settings": "🌬️ Matrix Gas Settings",
        "matrix_gas_type": "Matrix Gas Type",
        "total_pressure": "Total Pressure (torr)",
        "molecule_selection": "Molecule Selection",
        "concentration": "Concentration (ppb)",
        "run_simulation": "🧮 Run Mixed Spectrum",
        "run_analysis": "📈 Run Concentration Analysis",
        "calculating": "Calculating...",
        "results": "📊 Results",
        "mixed_spectrum": "🧪 Mixed Spectrum",
        "concentration_analysis": "📈 Concentration Analysis",
        "basic_hitran": "🌟 Basic HITRAN",
        "spectrometer": "🔬 Spectrometer",
        "fast": "⚡ Fast",
        "standard": "🎯 Standard",
        "high_resolution": "🔬 High Resolution",
        "maximum_resolution": "🚀 Maximum Resolution",
        "air": "Air",
        "cda": "Clean Dry Air (CDA)",
        "n2": "Nitrogen (N₂)",
        "o2": "Oxygen (O₂)",
        "he": "Helium (He)",
        "h2": "Hydrogen (H₂)",
        "ar": "Argon (Ar)",
        "co2": "Carbon Dioxide (CO₂)",
        "zero_air": "Zero Air",
        "experimental_data": "📁 Experimental Data",
        "line_analysis": "📋 Line Analysis",
        "parameter_sweep": "🌡️ Parameter Sweep",
        "export": "💾 Export",
        "upload_experimental": "Select Experimental Data File (CSV, TXT)",
        "data_preview": "Data Preview",
        "column_mapping": "Column Mapping",
        "wavelength_column": "Wavelength Column",
        "intensity_column": "Intensity Column",
        "data_type": "Data Type",
        "absorbance": "Absorbance",
        "transmittance": "Transmittance",
        "transmittance_percent": "Transmittance (%)",
        "experiment_vs_simulation": "🔍 Experiment vs Simulation",
        "show_experimental": "Show Experimental Data",
        "normalize_data": "Normalize Data",
        "comparison_statistics": "📊 Comparison Statistics",
        "correlation": "Correlation",
        "rms_error": "RMS Error",
        "mean_absolute_error": "Mean Absolute Error",
        "line_details": "📋 Line Details",
        "line_statistics": "📊 Line Statistics",
        "total_lines": "Total Lines",
        "average_wavelength": "Average Wavelength",
        "max_absorbance": "Max Absorbance",
        "frequency_range": "Frequency Range",
        "line_distribution": "📈 Line Distribution",
        "wavelength_distribution": "Wavelength Distribution",
        "frequency_distribution": "Frequency Distribution",
        "advanced_line_analysis": "🔬 Advanced Line Analysis",
        "analysis_type": "Analysis Type",
        "peak_analysis": "Peak Analysis",
        "spectrum_fitting": "Spectrum Fitting",
        "intensity_comparison": "Intensity Comparison",
        "temperature_dependence": "Temperature Dependence",
        "temperature_sweep": "🌡️ Temperature Sweep",
        "pressure_sweep": "🌬️ Pressure Sweep",
        "temperature_pressure_sweep": "🌡️🌬️ Temperature+Pressure Sweep",
        "sweep_type": "Sweep Type",
        "min_temperature": "Min Temperature (K)",
        "max_temperature": "Max Temperature (K)",
        "temperature_steps": "Temperature Steps",
        "fixed_pressure": "Fixed Pressure",
        "pressure": "Pressure (torr)",
        "min_pressure": "Min Pressure (torr)",
        "max_pressure": "Max Pressure (torr)",
        "pressure_steps": "Pressure Steps",
        "fixed_temperature": "Fixed Temperature",
        "temperature_range": "Temperature Range",
        "pressure_range": "Pressure Range",
        "run_sweep": "🌡️ Run Parameter Sweep",
        "sweep_calculating": "Calculating Parameter Sweep...",
        "sweep_results": "📊 Sweep Analysis Results",
        "temperature_sweep_spectrum": "Temperature Sweep Spectrum",
        "pressure_sweep_spectrum": "Pressure Sweep Spectrum",
        "max_absorbance_vs_temperature": "Max Absorbance vs Temperature",
        "peak_position_vs_temperature": "Peak Position vs Temperature",
        "temperature_dependence_analysis": "📈 Temperature Dependence Analysis",
        "temperature_sensitivity": "Temperature Sensitivity",
        "max_absorbance_vs_pressure": "Max Absorbance vs Pressure",
        "peak_position_vs_pressure": "Peak Position vs Pressure",
        "temperature_pressure_dependence": "Temperature-Pressure Dependence Heatmap",
        "temperature_pressure_3d": "Temperature-Pressure Dependence 3D Surface",
        "optimal_conditions": "🎯 Optimal Conditions",
        "optimal_temperature": "Optimal Temperature",
        "optimal_pressure": "Optimal Pressure",
        "csv_download": "📊 CSV Data Download",
        "png_download": "📈 PNG Graph Download",
        "pdf_download": "📄 PDF Report Download",
        "download_csv": "📥 Download CSV File",
        "download_png": "📥 Download PNG File",
        "language_selection": "🌐 Language Selection",
        "select_language": "Select Language",
        "no_data": "No data available",
        "no_results": "No results available",
        "error": "Error",
        "warning": "Warning",
        "info": "Information",
        "success": "Success",
        "loading": "Loading...",
        "please_wait": "Please wait...",
        "file_upload_error": "File upload error",
        "calculation_error": "Calculation error",
        "data_processing_error": "Data processing error",
        "feature_coming_soon": "This feature is coming soon",
        "single_molecule_only": "Available only in single molecule analysis mode",
        "run_simulation_first": "Please run simulation first",
        "no_experimental_data": "No experimental data in selected wavelength range",
        "no_simulation_results": "No simulation results to compare",
        "statistics_calculation_error": "Statistics calculation error",
        "fitting_error": "Fitting error"
    },
    "ja": {
        "title": "🔬 HITRAN CRDS シミュレーター",
        "simulation_settings": "⚙️ シミュレーション設定",
        "spectrometer_type": "分光器タイプ",
        "analysis_mode": "📊 解析モード",
        "temperature": "温度 (K)",
        "wavelength_min": "波長最小 (nm)",
        "wavelength_max": "波長最大 (nm)",
        "resolution_settings": "🔬 分解能設定",
        "resolution_mode": "分解能モード",
        "matrix_gas_settings": "🌬️ マトリックスガス設定",
        "matrix_gas_type": "マトリックスガスタイプ",
        "total_pressure": "全圧力 (torr)",
        "molecule_selection": "分子選択",
        "concentration": "濃度 (ppb)",
        "run_simulation": "🧮 混合スペクトル計算",
        "run_analysis": "📈 濃度別解析実行",
        "calculating": "計算中...",
        "results": "📊 結果",
        "mixed_spectrum": "🧪 混合スペクトル",
        "concentration_analysis": "📈 濃度別解析",
        "basic_hitran": "🌟 基本HITRAN",
        "spectrometer": "🔬 分光器",
        "fast": "⚡ 高速",
        "standard": "🎯 標準",
        "high_resolution": "🔬 高分解能",
        "maximum_resolution": "🚀 最大分解能",
        "air": "空気 (Air)",
        "cda": "清浄乾燥空気 (CDA)",
        "n2": "窒素 (N₂)",
        "o2": "酸素 (O₂)",
        "he": "ヘリウム (He)",
        "h2": "水素 (H₂)",
        "ar": "アルゴン (Ar)",
        "co2": "二酸化炭素 (CO₂)",
        "zero_air": "ゼロエア",
        "experimental_data": "📁 実験データ",
        "line_analysis": "📋 ライン解析",
        "parameter_sweep": "🌡️ パラメータスイープ",
        "export": "💾 エクスポート",
        "upload_experimental": "実験データファイル選択 (CSV, TXT)",
        "data_preview": "データプレビュー",
        "column_mapping": "カラムマッピング",
        "wavelength_column": "波長カラム選択",
        "intensity_column": "吸光度/透過度カラム選択",
        "data_type": "データタイプ",
        "absorbance": "吸光度 (Absorbance)",
        "transmittance": "透過度 (Transmittance)",
        "transmittance_percent": "透過率 (%)",
        "experiment_vs_simulation": "🔍 実験 vs シミュレーション比較",
        "show_experimental": "実験データ表示",
        "normalize_data": "データ正規化",
        "comparison_statistics": "📊 比較統計",
        "correlation": "相関係数",
        "rms_error": "RMS誤差",
        "mean_absolute_error": "平均絶対誤差",
        "line_details": "📋 ライン詳細",
        "line_statistics": "📊 ライン統計",
        "total_lines": "総ライン数",
        "average_wavelength": "平均波長",
        "max_absorbance": "最大吸光度",
        "frequency_range": "周波数範囲",
        "line_distribution": "📈 ライン分布",
        "wavelength_distribution": "波長分布",
        "frequency_distribution": "周波数分布",
        "advanced_line_analysis": "🔬 高度ライン解析",
        "analysis_type": "解析タイプ",
        "peak_analysis": "ピーク解析",
        "spectrum_fitting": "スペクトルフィッティング",
        "intensity_comparison": "強度比較",
        "temperature_dependence": "温度依存性",
        "temperature_sweep": "🌡️ 温度スイープ",
        "pressure_sweep": "🌬️ 圧力スイープ",
        "temperature_pressure_sweep": "🌡️🌬️ 温度+圧力スイープ",
        "sweep_type": "スイープタイプ",
        "min_temperature": "最小温度 (K)",
        "max_temperature": "最大温度 (K)",
        "temperature_steps": "温度ステップ数",
        "fixed_pressure": "固定圧力設定",
        "pressure": "圧力 (torr)",
        "min_pressure": "最小圧力 (torr)",
        "max_pressure": "最大圧力 (torr)",
        "pressure_steps": "圧力ステップ数",
        "fixed_temperature": "固定温度設定",
        "temperature_range": "温度範囲",
        "pressure_range": "圧力範囲",
        "run_sweep": "🌡️ パラメータスイープ実行",
        "sweep_calculating": "パラメータスイープ計算中...",
        "sweep_results": "📊 スイープ解析結果",
        "temperature_sweep_spectrum": "温度スイープスペクトル",
        "pressure_sweep_spectrum": "圧力スイープスペクトル",
        "max_absorbance_vs_temperature": "最大吸光度 vs 温度",
        "peak_position_vs_temperature": "ピーク位置 vs 温度",
        "temperature_dependence_analysis": "📈 温度依存性解析",
        "temperature_sensitivity": "温度感度",
        "max_absorbance_vs_pressure": "最大吸光度 vs 圧力",
        "peak_position_vs_pressure": "ピーク位置 vs 圧力",
        "temperature_pressure_dependence": "温度-圧力依存性ヒートマップ",
        "temperature_pressure_3d": "温度-圧力依存性3Dサーフェス",
        "optimal_conditions": "🎯 最適条件",
        "optimal_temperature": "最適温度",
        "optimal_pressure": "最適圧力",
        "csv_download": "📊 CSVデータダウンロード",
        "png_download": "📈 PNGグラフダウンロード",
        "pdf_download": "📄 PDFレポートダウンロード",
        "download_csv": "📥 CSVファイルダウンロード",
        "download_png": "📥 PNGファイルダウンロード",
        "language_selection": "🌐 言語選択",
        "select_language": "言語を選択してください",
        "no_data": "データがありません",
        "no_results": "結果がありません",
        "error": "エラー",
        "warning": "警告",
        "info": "情報",
        "success": "成功",
        "loading": "読み込み中...",
        "please_wait": "お待ちください...",
        "file_upload_error": "ファイルアップロードエラー",
        "calculation_error": "計算エラー",
        "data_processing_error": "データ処理エラー",
        "feature_coming_soon": "この機能は今後のアップデートで提供予定です",
        "single_molecule_only": "単一分子解析モードでのみ使用可能です",
        "run_simulation_first": "先にシミュレーションを実行してください",
        "no_experimental_data": "選択された波長範囲に実験データがありません",
        "no_simulation_results": "比較するシミュレーション結果がありません",
        "statistics_calculation_error": "統計計算エラー",
        "fitting_error": "フィッティングエラー"
    },
    "zh": {
        "title": "🔬 HITRAN CRDS 模拟器",
        "simulation_settings": "⚙️ 模拟设置",
        "spectrometer_type": "光谱仪类型",
        "analysis_mode": "📊 分析模式",
        "temperature": "温度 (K)",
        "wavelength_min": "波长最小 (nm)",
        "wavelength_max": "波长最大 (nm)",
        "resolution_settings": "🔬 分辨率设置",
        "resolution_mode": "分辨率模式",
        "matrix_gas_settings": "🌬️ 基质气体设置",
        "matrix_gas_type": "基质气体类型",
        "total_pressure": "总压力 (torr)",
        "molecule_selection": "分子选择",
        "concentration": "浓度 (ppb)",
        "run_simulation": "🧮 运行混合光谱",
        "run_analysis": "📈 运行浓度分析",
        "calculating": "计算中...",
        "results": "📊 结果",
        "mixed_spectrum": "🧪 混合光谱",
        "concentration_analysis": "📈 浓度分析",
        "basic_hitran": "🌟 基础HITRAN",
        "spectrometer": "🔬 光谱仪",
        "fast": "⚡ 快速",
        "standard": "🎯 标准",
        "high_resolution": "🔬 高分辨率",
        "maximum_resolution": "🚀 最大分辨率",
        "air": "空气 (Air)",
        "cda": "清洁干燥空气 (CDA)",
        "n2": "氮气 (N₂)",
        "o2": "氧气 (O₂)",
        "he": "氦气 (He)",
        "h2": "氢气 (H₂)",
        "ar": "氩气 (Ar)",
        "co2": "二氧化碳 (CO₂)",
        "zero_air": "零空气",
        "experimental_data": "📁 实验数据",
        "line_analysis": "📋 谱线分析",
        "parameter_sweep": "🌡️ 参数扫描",
        "export": "💾 导出",
        "upload_experimental": "选择实验数据文件 (CSV, TXT)",
        "data_preview": "数据预览",
        "column_mapping": "列映射",
        "wavelength_column": "波长列选择",
        "intensity_column": "吸光度/透射率列选择",
        "data_type": "数据类型",
        "absorbance": "吸光度 (Absorbance)",
        "transmittance": "透射率 (Transmittance)",
        "transmittance_percent": "透射率 (%)",
        "experiment_vs_simulation": "🔍 实验 vs 模拟比较",
        "show_experimental": "显示实验数据",
        "normalize_data": "数据归一化",
        "comparison_statistics": "📊 比较统计",
        "correlation": "相关系数",
        "rms_error": "RMS误差",
        "mean_absolute_error": "平均绝对误差",
        "line_details": "📋 谱线详情",
        "line_statistics": "📊 谱线统计",
        "total_lines": "总谱线数",
        "average_wavelength": "平均波长",
        "max_absorbance": "最大吸光度",
        "frequency_range": "频率范围",
        "line_distribution": "📈 谱线分布",
        "wavelength_distribution": "波长分布",
        "frequency_distribution": "频率分布",
        "advanced_line_analysis": "🔬 高级谱线分析",
        "analysis_type": "分析类型",
        "peak_analysis": "峰值分析",
        "spectrum_fitting": "光谱拟合",
        "intensity_comparison": "强度比较",
        "temperature_dependence": "温度依赖性",
        "temperature_sweep": "🌡️ 温度扫描",
        "pressure_sweep": "🌬️ 压力扫描",
        "temperature_pressure_sweep": "🌡️🌬️ 温度+压力扫描",
        "sweep_type": "扫描类型",
        "min_temperature": "最小温度 (K)",
        "max_temperature": "最大温度 (K)",
        "temperature_steps": "温度步数",
        "fixed_pressure": "固定压力设置",
        "pressure": "压力 (torr)",
        "min_pressure": "最小压力 (torr)",
        "max_pressure": "最大压力 (torr)",
        "pressure_steps": "压力步数",
        "fixed_temperature": "固定温度设置",
        "temperature_range": "温度范围",
        "pressure_range": "压力范围",
        "run_sweep": "🌡️ 运行参数扫描",
        "sweep_calculating": "计算参数扫描中...",
        "sweep_results": "📊 扫描分析结果",
        "temperature_sweep_spectrum": "温度扫描光谱",
        "pressure_sweep_spectrum": "压力扫描光谱",
        "max_absorbance_vs_temperature": "最大吸光度 vs 温度",
        "peak_position_vs_temperature": "峰值位置 vs 温度",
        "temperature_dependence_analysis": "📈 温度依赖性分析",
        "temperature_sensitivity": "温度敏感性",
        "max_absorbance_vs_pressure": "最大吸光度 vs 压力",
        "peak_position_vs_pressure": "峰值位置 vs 压力",
        "temperature_pressure_dependence": "温度-压力依赖性热图",
        "temperature_pressure_3d": "温度-压力依赖性3D表面",
        "optimal_conditions": "🎯 最佳条件",
        "optimal_temperature": "最佳温度",
        "optimal_pressure": "最佳压力",
        "csv_download": "📊 CSV数据下载",
        "png_download": "📈 PNG图表下载",
        "pdf_download": "📄 PDF报告下载",
        "download_csv": "📥 下载CSV文件",
        "download_png": "📥 下载PNG文件",
        "language_selection": "🌐 语言选择",
        "select_language": "请选择语言",
        "no_data": "没有数据",
        "no_results": "没有结果",
        "error": "错误",
        "warning": "警告",
        "info": "信息",
        "success": "成功",
        "loading": "加载中...",
        "please_wait": "请稍候...",
        "file_upload_error": "文件上传错误",
        "calculation_error": "计算错误",
        "data_processing_error": "数据处理错误",
        "feature_coming_soon": "此功能将在未来更新中提供",
        "single_molecule_only": "仅在单分子分析模式下可用",
        "run_simulation_first": "请先运行模拟",
        "no_experimental_data": "选定波长范围内没有实验数据",
        "no_simulation_results": "没有可比较的模拟结果",
        "statistics_calculation_error": "统计计算错误",
        "fitting_error": "拟合错误"
    }
}

def get_language_selector() -> str:
    """언어 선택기"""
    st.sidebar.markdown("---")
    st.sidebar.subheader("🌐 언어 선택")
    
    selected_language = st.sidebar.selectbox(
        "언어를 선택하세요",
        list(SUPPORTED_LANGUAGES.keys()),
        index=0
    )
    
    return SUPPORTED_LANGUAGES[selected_language]

def get_text(key: str, language: str = "ko") -> str:
    """번역된 텍스트 가져오기"""
    if language in TRANSLATIONS and key in TRANSLATIONS[language]:
        return TRANSLATIONS[language][key]
    else:
        # 번역이 없으면 한국어로 fallback
        return TRANSLATIONS.get("ko", {}).get(key, key)

def initialize_language() -> str:
    """언어 초기화"""
    if 'language' not in st.session_state:
        st.session_state.language = "ko"
    
    return st.session_state.language

def set_language(language: str) -> None:
    """언어 설정"""
    st.session_state.language = language

def get_current_language() -> str:
    """현재 언어 가져오기"""
    return st.session_state.get('language', 'ko') 